# Generated by Django 3.2.5 on 2021-08-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_gold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('house', models.CharField(max_length=45)),
                ('pet', models.CharField(max_length=45)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
