# Generated by Django 3.2.5 on 2021-08-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_gold', '0004_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='email',
            field=models.EmailField(max_length=45),
        ),
    ]
